name: polaris_domain
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  riverpod: ^0.12.1
  equatable: ^1.2.5
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
