name: CI

on: [push, pull_request]

jobs:
  check-code-style-and-run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        - packages/polaris_core
        - packages/polaris_domain
        - packages/polaris_data
        - packages/polaris_ui

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Check formatting
        run: flutter format --set-exit-if-changed --dry-run .
        working-directory: ${{ matrix.package }}

      - name: Get packages
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Analyze source code
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ matrix.package }}
