name: CI

on: [push, pull_request]

jobs:
  check-code-style-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Check formatting
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Get packages
        run: flutter pub get

      - name: Analyze source code
        run: flutter analyze

      - name: Run tests
        run: flutter test
